"""create all tables

Revision ID: 865257416bfb
Revises: fec61226dcfa
Create Date: 2026-06-14 13:15:39.597324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '865257416bfb'
down_revision = 'fec61226dcfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=False)
        batch_op.create_index('ix_users_role', ['role'], unique=False)

    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('capacity', sa.Float(), nullable=False),
    sa.Column('current_load', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warehouses_location'), ['location'], unique=False)
        batch_op.create_index('ix_warehouses_name', ['name'], unique=False)

    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index('ix_password_reset_tokens_token', ['token'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_jti', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index('ix_refresh_tokens_token_jti', ['token_jti'], unique=False)
        batch_op.create_index('ix_refresh_tokens_user_id', ['user_id'], unique=False)

    op.create_table('shipments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tracking_id', sa.String(length=50), nullable=False),
    sa.Column('sender_name', sa.String(length=120), nullable=False),
    sa.Column('sender_phone', sa.String(length=20), nullable=False),
    sa.Column('receiver_name', sa.String(length=120), nullable=False),
    sa.Column('receiver_phone', sa.String(length=20), nullable=False),
    sa.Column('package_type', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('delivery_address', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.create_index('ix_shipments_agent_id', ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_shipments_customer_id', ['customer_id'], unique=False)
        batch_op.create_index('ix_shipments_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_tracking_id'), ['tracking_id'], unique=True)
        batch_op.create_index('ix_shipments_warehouse_id', ['warehouse_id'], unique=False)

    op.create_table('delivery_proofs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('proof_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_proofs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_proofs_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_delivery_proofs_shipment_id', ['shipment_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_notifications_is_read', ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_shipment_id'), ['shipment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('tracking_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tracking_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracking_history_shipment_id'), ['shipment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracking_history_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracking_history_updated_by'), ['updated_by'], unique=False)
        batch_op.create_index('ix_tracking_shipment_id', ['shipment_id'], unique=False)
        batch_op.create_index('ix_tracking_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ix_tracking_updated_by', ['updated_by'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracking_history', schema=None) as batch_op:
        batch_op.drop_index('ix_tracking_updated_by')
        batch_op.drop_index('ix_tracking_timestamp')
        batch_op.drop_index('ix_tracking_shipment_id')
        batch_op.drop_index(batch_op.f('ix_tracking_history_updated_by'))
        batch_op.drop_index(batch_op.f('ix_tracking_history_timestamp'))
        batch_op.drop_index(batch_op.f('ix_tracking_history_shipment_id'))

    op.drop_table('tracking_history')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_shipment_id'))
        batch_op.drop_index('ix_notifications_is_read')
        batch_op.drop_index('ix_notifications_created_at')

    op.drop_table('notifications')
    with op.batch_alter_table('delivery_proofs', schema=None) as batch_op:
        batch_op.drop_index('ix_delivery_proofs_shipment_id')
        batch_op.drop_index(batch_op.f('ix_delivery_proofs_created_at'))

    op.drop_table('delivery_proofs')
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_index('ix_shipments_warehouse_id')
        batch_op.drop_index(batch_op.f('ix_shipments_tracking_id'))
        batch_op.drop_index('ix_shipments_status')
        batch_op.drop_index('ix_shipments_customer_id')
        batch_op.drop_index(batch_op.f('ix_shipments_created_at'))
        batch_op.drop_index('ix_shipments_agent_id')

    op.drop_table('shipments')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_refresh_tokens_user_id')
        batch_op.drop_index('ix_refresh_tokens_token_jti')

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))
        batch_op.drop_index('ix_password_reset_tokens_token')

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_index('ix_warehouses_name')
        batch_op.drop_index(batch_op.f('ix_warehouses_location'))

    op.drop_table('warehouses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_role')
        batch_op.drop_index(batch_op.f('ix_users_name'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
