"""init

Revision ID: e3e7586ce9d6
Revises: 865257416bfb
Create Date: 2026-06-18 20:16:05.865014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3e7586ce9d6'
down_revision = '865257416bfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouses_name'))
        batch_op.create_index(batch_op.f('ix_warehouses_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouses_name'))
        batch_op.create_index(batch_op.f('ix_warehouses_name'), ['name'], unique=False)

    # ### end Alembic commands ###
